[[ -z "$TMUX" ]] && tmux
bindkey '^ ' autosuggest-accept
bindkey '^[^M' autosuggest-execute
bindkey "^k" history-beginning-search-backward
bindkey "^j" history-beginning-search-forward
if [ ! -S ~/.ssh/ssh_auth_sock ]; then
  eval `ssh-agent`
  ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
ssh-add -l > /dev/null || ssh-add
