if [[ -z "$ZELLIJ" ]]; then
    if [[ "$ZELLIJ_AUTO_ATTACH" == "true" ]]; then
        zellij attach -c
    else
        zellij
    fi

    if [[ "$ZELLIJ_AUTO_EXIT" == "true" ]]; then
        exit
    fi
fi

bindkey '^@' autosuggest-accept
bindkey '^[^M' autosuggest-execute
bindkey "^k" history-beginning-search-backward
bindkey "^j" history-beginning-search-forward

# Add ssh key to agent if not already added
ssh-add -l > /dev/null || ssh-add

# Source zsh config when creating a new nix shell
if [ "$IN_NIX_SHELL" = "impure" ]; then
  source ~/.zshrc
fi
