name: Check Flake

on:
  pull_request:
    paths-ignore:
      - .github/**
      - '!.github/workflows/check-flake.yaml'
      - LICENCE
      - README.md
  push:
    paths-ignore:
      - .github/**
      - '!.github/workflows/check-flake.yaml'
      - LICENCE
      - README.md

jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v9
        with:
          nixpkgs-keys: nixpkgs-master,nixpkgs-stable,nixpkgs-unstable

  check-flake-systems:
    name: Check Flake Systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Check Nix flake systems
        run: |
          {
            echo '```bash'
            nix flake check --all-systems 2>&1
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
