name: Check Flake

on:
  pull_request:
    paths-ignore:
      - .github/**
      - '!.github/workflows/check-flake.yaml'
      - LICENCE
      - README.md
  push:
    paths-ignore:
      - .github/**
      - '!.github/workflows/check-flake.yaml'
      - LICENCE
      - README.md

jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Install jq via Nix
        run: nix profile install nixpkgs#jq

      - name: Extract nixpkgs keys from flake.lock
        id: extract-keys
        shell: bash
        run: |
          nixpkgs_keys=$(jq --raw-output '.nodes.root.inputs | keys | join(",")' flake.lock)
          echo "Extracted nixpkgs keys: $nixpkgs_keys"
          echo "nixpkgs_keys=$nixpkgs_keys" >> $GITHUB_OUTPUT

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v9
        with:
          nixpkgs-keys: ${{ steps.extract-keys.outputs.nixpkgs_keys }}

  check-flake-systems:
    name: Check Flake Systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Check Nix flake systems
        run: |
          {
            echo '```bash'
            nix flake check --all-systems 2>&1
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
