name: CI Checks

on:
  pull_request:
  push:

jobs:
  check-flake:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
      
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Check Nix flake inputs
      uses: DeterminateSystems/flake-checker-action@v5

