name: Check Flake

on:
  pull_request:
    paths-ignore:
      - .github/**
      - LICENCE
      - README.md
  push:
    paths-ignore:
      - .github/**
      - LICENCE
      - README.md

jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository
      uses: actions/checkout@v4

    - name: Check Nix flake inputs
      uses: DeterminateSystems/flake-checker-action@v5

  check-flake-systems:
    name: Check Flake Systems
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24

    - name: Check Nix flake systems
      run: |
        {
          echo '```bash'
          nix flake check --all-systems 2>&1
          echo '```'
        } >> $GITHUB_STEP_SUMMARY

