name: Update README with Directory Tree and flake output

on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENCE
      - README.md
      - flake.nix
      - flake.lock

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash # To get `set -o pipefail`

jobs:
  update-readme:
    name: Generate output and update README.md
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v15

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Install tree using Nix
        run: nix profile install nixpkgs#tree

      - name: Generate directory tree
        run: tree -a --filesfirst --noreport -I '.git|LICENSE|README.md|tree.txt|default.nix|wallpapers' > tree.txt

      - name: Generate flake output
        run: nix flake show | awk '/nixosConfigurations/{flag=1} flag' | sed 's/\x1b\[[0-9;]*m//g' > flake.txt

      - name: Update README
        run: |
          cp README.md README.md.bak
          awk '/<!--START_SECTION:tree-->/ {print; print "```bash"; system("cat tree.txt"); print "```"; skip=1; next}
               /<!--END_SECTION:tree-->/ {skip=0} !skip' README.md.bak > temp.md
          mv temp.md README.md.bak
          awk '/<!--START_SECTION:flake-->/ {print; print "```bash"; system("cat flake.txt"); print "```"; skip=1; next}
               /<!--END_SECTION:flake-->/ {skip=0} !skip' README.md.bak > README.md
          cat README.md

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m ":memo: (readme): Automatically update directory tree and flake output"
            git pull --rebase
            git push
          fi
