name: Update README with Directory Tree and flake show

on:
  push:
    paths:
      - '**/*'

jobs:
  tree:
    name: Generate tree of repository and add it to README.md
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install tree using Nix
      run: nix-env --file '<nixpkgs>' --install tree

    - name: Generate directory tree
      run: tree -a --noreport --filesfirst --prune -I '.git|LICENSE|README.md|tree.txt' | tee tree.txt

    - name: Update README
      run: |
        {
          sed '/<!--START_SECTION:tree-->/q' README.md
          echo '```bash'
          cat tree.txt
          echo '```'
          sed -n '/<!--END_SECTION:tree-->/,$p' README.md
        } > new_README.md
        
        cat new_README.md
        mv new_README.md README.md

    - name: Commit and push if changed
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git diff --staged --quiet || git commit -m "Automatically update directory tree"
        git push

  flake:
    name: Generate flake outputs and add it to README.md
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v24

    - name: Generate flake output
      run: nix flake show | awk '/nixosConfigurations/{flag=1} flag' | tee flake.txt

    - name: Update README
      run: |
        {
          sed '/<!--START_SECTION:flake-->/q' README.md
          echo '```bash'
          nix flake show | awk '/nixosConfigurations/{flag=1} flag'
          echo '```'
          sed -n '/<!--END_SECTION:flake-->/,$p' README.md
        } > new_README.md

        cat new_README.md
        mv new_README.md README.md

    - name: Commit and push if changed
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git diff --staged --quiet || git commit -m "Automatically update flake output"
        git push

