name: Update flake

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - run: nix flake update
      - run: |
          {
            echo "# Changes after updating flake"
            echo '```diff'
            git diff main || true
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
